spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
      username: xueguoxue
      password: xueguoxue
      url: jdbc:mysql://172.16.9.15:3306/aop
      driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 172.16.9.15
      port: 27017
      database: aop-demo
      repositories:
        enabled: true